import { db } from '../src/lib/db';
import bcrypt from 'bcryptjs';

export const ALLOWED_BRANDS = [
  'Titan',
  'Fastrack',
  'Sonata',
  'Timex',
  'Casio',
  'Fossil',
  'Seiko',
  'Citizen',
  'Tissot',
  'TAG Heuer',
  'Rado',
  'Omega',
] as const;

export const INITIAL_PRODUCTS = [
  {
    slug: 'seiko-presage-cocktail-time-srpb43j1',
    name: 'Presage Cocktail Time',
    modelName: 'Presage Cocktail Time',
    brand: 'Seiko',
    referenceNumber: 'SRPB43J1',
    price: 45000,
    purchaseValue: 45000,
    currency: 'INR',
    images: ['/watches/seiko-presage-srpb43j1.svg'],
    imageUrl: '/watches/seiko-presage-srpb43j1.svg',
    description: 'Inspired by the glamour of Tokyo cocktail bars. Features an ice-blue sunburst guilloché dial, polished dauphine hands, blued steel second hand, and a box-shaped Hardlex crystal.',
    craftsmanshipNarrative: 'Powered by the Seiko 4R35 mechanical automatic calibre with 41-hour power reserve, manual-winding capability, and hacking seconds.',
    movementType: 'Automatic',
    movementCaliber: 'Cal. 4R35',
    powerReserve: '41 hours',
    caseMaterial: 'Stainless Steel',
    caseSize: '40.5 mm',
    caseThickness: '11.8 mm',
    dialColor: 'Ice Blue Sunburst',
    crystal: 'Box-shaped Hardlex',
    waterResistance: '50m / 5 bar',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 8,
    stock: 8,
    collection: 'Presage',
    tags: ['cocktail-time', 'dress', 'sunburst', 'mechanical'],
    isActive: true,
  },
  {
    slug: 'titan-edge-ceramic-slim-1696qc01',
    name: 'Edge Ceramic Slim',
    modelName: 'Edge Ceramic Slim',
    brand: 'Titan',
    referenceNumber: '1696QC01',
    price: 24995,
    purchaseValue: 24995,
    currency: 'INR',
    images: ['/watches/titan-edge.svg'],
    imageUrl: '/watches/titan-edge.svg',
    description: 'One of the slimmest ceramic watches in the world at just 4.4 mm total thickness. Hypoallergenic high-tech ceramic case and bracelet with a pure minimalist dial.',
    craftsmanshipNarrative: 'Engineered with Titan’s proprietary ultra-slim Edge quartz movement with state-of-the-art precision regulation.',
    movementType: 'Quartz',
    movementCaliber: 'Titan Ultra-Slim Edge Calibre',
    powerReserve: '2 years battery',
    caseMaterial: 'High-Tech Ceramic',
    caseSize: '40 mm',
    caseThickness: '4.4 mm',
    dialColor: 'Anthracite Black',
    crystal: 'Sapphire Crystal',
    waterResistance: '30m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 6,
    stock: 6,
    collection: 'Edge',
    tags: ['ultra-slim', 'ceramic', 'contemporary', 'titan'],
    isActive: true,
  },
  {
    slug: 'fastrack-reflex-play-38072ap01',
    name: 'Reflex Play Analog-Digital',
    modelName: 'Reflex Play Analog-Digital',
    brand: 'Fastrack',
    referenceNumber: '38072AP01',
    price: 4495,
    purchaseValue: 4495,
    currency: 'INR',
    images: ['/watches/fastrack-reflex.svg'],
    imageUrl: '/watches/fastrack-reflex.svg',
    description: 'Dynamic sports timepiece combining analog hand tracking with digital LCD stopwatch, alarm, and second-timezone instrumentation.',
    craftsmanshipNarrative: 'Impact-resistant matte resin case with reinforced mineral crystal and sweat-wicking silicone strap.',
    movementType: 'Quartz',
    movementCaliber: 'Dual Time Ana-Digi Module',
    powerReserve: '3 years battery',
    caseMaterial: 'Impact Resin & Steel Back',
    caseSize: '44 mm',
    caseThickness: '13.5 mm',
    dialColor: 'Matte Stealth Black / Crimson',
    crystal: 'Hardened Mineral',
    waterResistance: '100m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 15,
    stock: 15,
    collection: 'Reflex',
    tags: ['sport', 'dual-time', 'analog-digital', 'active'],
    isActive: true,
  },
  {
    slug: 'sonata-volt-champagne-classic-77083ym01',
    name: 'Volt Champagne Classic',
    modelName: 'Volt Champagne Classic',
    brand: 'Sonata',
    referenceNumber: '77083YM01',
    price: 1895,
    purchaseValue: 1895,
    currency: 'INR',
    images: ['/watches/sonata-volt.svg'],
    imageUrl: '/watches/sonata-volt.svg',
    description: 'Timeless traditional formal watch with a shimmering champagne dial, gold-polished fluted case, and durable stainless steel link bracelet.',
    craftsmanshipNarrative: 'Engineered for enduring reliability with a high-accuracy quartz oscillator and mineral glass.',
    movementType: 'Quartz',
    movementCaliber: 'Japanese Quartz Calibre',
    powerReserve: '3 years battery',
    caseMaterial: 'Gold-Ion Plated Alloy',
    caseSize: '39 mm',
    caseThickness: '8.8 mm',
    dialColor: 'Sunray Champagne Gold',
    crystal: 'Mineral Glass',
    waterResistance: '30m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 20,
    stock: 20,
    collection: 'Volt',
    tags: ['classic', 'gold', 'formal', 'dress'],
    isActive: true,
  },
  {
    slug: 'timex-q-timex-reissue-1979-tw2t80700',
    name: 'Q Timex Reissue 1979',
    modelName: 'Q Timex Reissue 1979',
    brand: 'Timex',
    referenceNumber: 'TW2T80700',
    price: 13995,
    purchaseValue: 13995,
    currency: 'INR',
    images: ['/watches/timex-q.svg'],
    imageUrl: '/watches/timex-q.svg',
    description: 'Faithful recreation of the iconic 1979 quartz diver. Features a bidirectional red and blue "Pepsi" rotating ring, woven stainless steel bracelet, functional battery hatch, and domed acrylic crystal.',
    craftsmanshipNarrative: 'Period-correct vintage geometry featuring hooded lugs and luminous dial geometry.',
    movementType: 'Quartz',
    movementCaliber: 'Seiko Epson Quartz Calibre',
    powerReserve: '3 years battery with coin-slot hatch',
    caseMaterial: 'Stainless Steel',
    caseSize: '38 mm',
    caseThickness: '11.5 mm',
    dialColor: 'Matte Deep Blue',
    crystal: 'Domed Acrylic',
    waterResistance: '50m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 10,
    stock: 10,
    collection: 'Q Timex',
    tags: ['pepsi-bezel', 'retro', 'heritage', 'woven-steel'],
    isActive: true,
  },
  {
    slug: 'casio-g-shock-octagonal-ga-2100-1a1dr',
    name: 'G-Shock Octagonal "CasiOak"',
    modelName: 'G-Shock Octagonal "CasiOak"',
    brand: 'Casio',
    referenceNumber: 'GA-2100-1A1DR',
    price: 9195,
    purchaseValue: 9195,
    currency: 'INR',
    images: ['/watches/casio-ga2100.svg'],
    imageUrl: '/watches/casio-ga2100.svg',
    description: 'The world-famous octagonal Carbon Core Guard G-Shock in full stealth matte black. Ultra-thin 11.8mm profile with extraordinary shock resistance.',
    craftsmanshipNarrative: 'Carbon Core Guard structure protects the internal module by enclosing it in a carbon-reinforced fine resin case.',
    movementType: 'Quartz',
    movementCaliber: 'Casio Module 5611',
    powerReserve: '3 years battery',
    caseMaterial: 'Carbon / Resin',
    caseSize: '45.4 mm',
    caseThickness: '11.8 mm',
    dialColor: 'Stealth Blackout',
    crystal: 'Mineral Glass',
    waterResistance: '200m / 20 bar',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 12,
    stock: 12,
    collection: 'G-Shock Carbon Core',
    tags: ['casioak', 'stealth', 'carbon-core', 'shockproof'],
    isActive: true,
  },
  {
    slug: 'fossil-townsman-automatic-skeleton-me3098',
    name: 'Townsman Automatic Skeleton',
    modelName: 'Townsman Automatic Skeleton',
    brand: 'Fossil',
    referenceNumber: 'ME3098',
    price: 18995,
    purchaseValue: 18995,
    currency: 'INR',
    images: ['/watches/fossil-townsman.svg'],
    imageUrl: '/watches/fossil-townsman.svg',
    description: 'Striking open-work skeleton dial revealing the intricate balance wheel and gear train. Rose gold accents contrasted with a rich amber leather strap.',
    craftsmanshipNarrative: 'Rotor-powered automatic self-winding movement with exhibition case back showing full mechanical operation.',
    movementType: 'Automatic',
    movementCaliber: 'Miyota Skeleton Automatic',
    powerReserve: '40 hours',
    caseMaterial: 'Stainless Steel',
    caseSize: '44 mm',
    caseThickness: '12 mm',
    dialColor: 'Skeleton / Rose Gold & Charcoal',
    crystal: 'Hardened Mineral',
    waterResistance: '50m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 7,
    stock: 7,
    collection: 'Townsman',
    tags: ['skeleton', 'mechanical', 'rose-gold', 'leather'],
    isActive: true,
  },
  {
    slug: 'citizen-promaster-marine-eco-drive-bn0150-28e',
    name: 'Promaster Marine Eco-Drive Diver',
    modelName: 'Promaster Marine Eco-Drive Diver',
    brand: 'Citizen',
    referenceNumber: 'BN0150-28E',
    price: 28500,
    purchaseValue: 28500,
    currency: 'INR',
    images: ['/watches/citizen-promaster.svg'],
    imageUrl: '/watches/citizen-promaster.svg',
    description: 'ISO 6425 compliant professional saturation dive watch. Powered by any light source via Eco-Drive technology, never requiring a battery change.',
    craftsmanshipNarrative: 'Features an oversized high-visibility luminous handset, 60-click unidirectional ratcheting bezel, and screw-down crown at 4 o’clock.',
    movementType: 'Eco-Drive Solar',
    movementCaliber: 'Calibre E168 Eco-Drive',
    powerReserve: '6 months on full light charge',
    caseMaterial: 'Stainless Steel',
    caseSize: '44 mm',
    caseThickness: '11.5 mm',
    dialColor: 'Matte Deep Black',
    crystal: 'Anti-Reflective Mineral Crystal',
    waterResistance: '200m Diver ISO Compliant',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 9,
    stock: 9,
    collection: 'Promaster',
    tags: ['diver', 'eco-drive', 'solar', 'iso-certified'],
    isActive: true,
  },
  {
    slug: 'tissot-prx-powermatic-80-t137-407-11-041-00',
    name: 'PRX Powermatic 80',
    modelName: 'PRX Powermatic 80',
    brand: 'Tissot',
    referenceNumber: 'T137.407.11.041.00',
    price: 68000,
    purchaseValue: 68000,
    currency: 'INR',
    images: ['/watches/tissot-prx.svg'],
    imageUrl: '/watches/tissot-prx.svg',
    description: 'The defining integrated-bracelet sports watch of our era. 1978 retro tonneau silhouette with a deeply textured blue waffle dial and exhibition sapphire caseback.',
    craftsmanshipNarrative: 'Equipped with the groundbreaking Swiss Powermatic 80 calibre with 80 hours of power reserve and anti-magnetic Nivachron hairspring.',
    movementType: 'Automatic',
    movementCaliber: 'Powermatic 80.111',
    powerReserve: '80 hours',
    caseMaterial: '316L Stainless Steel',
    caseSize: '40 mm',
    caseThickness: '10.9 mm',
    dialColor: 'Waffle Embossed Blue',
    crystal: 'Scratch-resistant Sapphire Crystal',
    waterResistance: '100m / 10 bar',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 5,
    stock: 5,
    collection: 'PRX',
    tags: ['integrated-bracelet', 'swiss-made', 'powermatic-80', 'blue-dial'],
    isActive: true,
  },
  {
    slug: 'tag-heuer-carrera-chronograph-cbs2210-fc6534',
    name: 'Carrera Chronograph Glassbox',
    modelName: 'Carrera Chronograph Glassbox',
    brand: 'TAG Heuer',
    referenceNumber: 'CBS2210.FC6534',
    price: 560000,
    purchaseValue: 560000,
    currency: 'INR',
    images: ['/watches/tag-heuer-carrera.svg'],
    imageUrl: '/watches/tag-heuer-carrera.svg',
    description: '60th anniversary glassbox edition with seamless domed sapphire crystal curving over the tachymeter scale. Reverse panda tri-compax layout with perforated leather racing strap.',
    craftsmanshipNarrative: 'Manufacture Calibre TH20-00 automatic chronograph with bidirectional winding rotor and 80-hour power reserve.',
    movementType: 'Automatic',
    movementCaliber: 'Heuer 02 / TH20-00 In-House',
    powerReserve: '80 hours',
    caseMaterial: 'Fine-brushed / Polished Stainless Steel',
    caseSize: '39 mm',
    caseThickness: '13.86 mm',
    dialColor: 'Signature Glassbox Black & Silver',
    crystal: 'Domed Beveled Sapphire Crystal',
    waterResistance: '100m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 4,
    stock: 4,
    collection: 'Carrera',
    tags: ['chronograph', 'motorsport', 'glassbox', 'in-house'],
    isActive: true,
  },
  {
    slug: 'rado-captain-cook-automatic-r32505313',
    name: 'Captain Cook Automatic',
    modelName: 'Captain Cook Automatic',
    brand: 'Rado',
    referenceNumber: 'R32505313',
    price: 215000,
    purchaseValue: 215000,
    currency: 'INR',
    images: ['/watches/rado-captain-cook.svg'],
    imageUrl: '/watches/rado-captain-cook.svg',
    description: 'Vintage diver aesthetics fused with Rado’s Master of Materials innovation. Features an inward-sloping high-tech ceramic bezel insert, sunbrushed gradient green dial, and swinging red anchor.',
    craftsmanshipNarrative: 'Swiss automatic calibre with 80 hours power reserve and Nivachron anti-magnetic balance spring.',
    movementType: 'Automatic',
    movementCaliber: 'Calibre R763',
    powerReserve: '80 hours',
    caseMaterial: 'Stainless Steel & High-Tech Ceramic',
    caseSize: '42 mm',
    caseThickness: '12.3 mm',
    dialColor: 'Sunbrushed Forest Green',
    crystal: 'Box Sapphire with Anti-Reflective Coating',
    waterResistance: '300m / 30 bar',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 4,
    stock: 4,
    collection: 'Captain Cook',
    tags: ['high-tech-ceramic', 'vintage-diver', 'swiss-made', 'green-dial'],
    isActive: true,
  },
  {
    slug: 'omega-speedmaster-professional-moonwatch-31030425001002',
    name: 'Speedmaster Professional Moonwatch',
    modelName: 'Speedmaster Professional Moonwatch',
    brand: 'Omega',
    referenceNumber: '310.30.42.50.01.002',
    price: 790000,
    purchaseValue: 790000,
    currency: 'INR',
    images: ['/watches/omega-speedmaster.svg'],
    imageUrl: '/watches/omega-speedmaster.svg',
    description: 'The legendary Moonwatch. Direct descendant of the timepiece flight-qualified by NASA for all manned lunar expeditions. Features the anodised aluminium bezel ring with "Dot over 90".',
    craftsmanshipNarrative: 'Powered by the Master Chronometer-certified Calibre 3861 manual-wind movement, resistant to magnetic fields reaching 15,000 gauss.',
    movementType: 'Manual Wind',
    movementCaliber: 'Co-Axial Master Chronometer Cal. 3861',
    powerReserve: '50 hours',
    caseMaterial: 'Stainless Steel',
    caseSize: '42 mm',
    caseThickness: '13.2 mm',
    dialColor: 'Step Matte Black',
    crystal: 'Sapphire Crystal with Anti-Reflective Treatment',
    waterResistance: '50m',
    condition: 'New',
    year: 2024,
    inStock: true,
    stockCount: 3,
    stock: 3,
    collection: 'Speedmaster',
    tags: ['moonwatch', 'nasa', 'co-axial', 'chronograph'],
    isActive: true,
  },
];

async function main() {
  console.log('--- Wristloom Watch Catalog Seeding ---');

  // 1. Deactivate old demo brands (Rolex, Patek Philippe, Audemars Piguet, Cartier, IWC, etc.)
  console.log('Sanitizing catalog: deactivating demo products from unapproved brands...');
  const oldProducts = await db.product.findMany({
    where: {
      brand: { notIn: ALLOWED_BRANDS as unknown as string[] },
    },
  });

  if (oldProducts.length > 0) {
    console.log(`Found ${oldProducts.length} legacy demo products. Setting to inactive...`);
    await db.product.updateMany({
      where: {
        brand: { notIn: ALLOWED_BRANDS as unknown as string[] },
      },
      data: {
        isActive: false,
        inStock: false,
      },
    });
  }

  // 2. Upsert the 12 authorized watch products
  console.log(`Seeding 12 authorized brand products into PostgreSQL database...`);
  for (const prod of INITIAL_PRODUCTS) {
    await db.product.upsert({
      where: { slug: prod.slug },
      update: prod,
      create: prod,
    });
    console.log(`✓ Seeded ${prod.brand} — ${prod.name} (${prod.referenceNumber})`);
  }

  const activeCount = await db.product.count({ where: { isActive: true } });
  console.log(`✓ Active watch catalog count: ${activeCount}`);

  // 3. Admin & Technician accounts
  console.log('Seeding dedicated Admin and Technician accounts...');
  const adminPasswordHash = await bcrypt.hash('Admin@wristloom2026', 12);
  const adminUser = await db.user.upsert({
    where: { email: 'wristloom@gmail.com' },
    update: {
      role: 'ADMIN',
      name: 'Wristloom Administrator',
      passwordHash: adminPasswordHash,
    },
    create: {
      email: 'wristloom@gmail.com',
      name: 'Wristloom Administrator',
      passwordHash: adminPasswordHash,
      role: 'ADMIN',
      phone: '+91 98765 00001',
    },
  });
  console.log(`✓ Seeded dedicated Admin: ${adminUser.email} (Role: ${adminUser.role})`);

  const techPasswordHash = await bcrypt.hash('Tech@wristloom2026', 12);
  const techUser = await db.user.upsert({
    where: { email: 'technician@wristloom.com' },
    update: {
      role: 'TECHNICIAN',
      name: 'Arjun Mehta',
      passwordHash: techPasswordHash,
    },
    create: {
      email: 'technician@wristloom.com',
      name: 'Arjun Mehta',
      passwordHash: techPasswordHash,
      role: 'TECHNICIAN',
      phone: '+91 98765 00002',
    },
  });

  await db.technician.upsert({
    where: { userId: techUser.id },
    update: {
      isAvailable: true,
      isVerified: true,
      rating: 4.95,
      yearsExperience: 12,
      brandsServiced: ['Seiko', 'Tissot', 'TAG Heuer', 'Rado', 'Omega', 'Titan'],
    },
    create: {
      userId: techUser.id,
      bio: 'Certified Master Horologist specializing in Japanese and Swiss precision overhauls.',
      yearsExperience: 12,
      specializations: ['Master Chronometer Regulation', 'Co-Axial Overhauls', 'Ceramic Case Refurbishment'],
      brandsServiced: ['Seiko', 'Tissot', 'TAG Heuer', 'Rado', 'Omega', 'Titan'],
      rating: 4.95,
      completedServices: 184,
      isVerified: true,
      isAvailable: true,
      currentLatitude: 18.9667,
      currentLongitude: 72.8081,
    },
  });
  console.log(`✓ Seeded Master Horologist: ${techUser.email} (Role: ${techUser.role})`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  });
