// ============================================================
// Wristloom — Realistic Mock Data
// All images use high-quality Unsplash URLs for luxury watches
// ============================================================

import type {
  VaultItem,
  Technician,
  Product,
  TradeInRequest,
  AppraisalRequest,
  Review,
  Testimonial,
  Workshop,
  RestorationProject,
  CommunityPost,
  FAQItem,
  Location,
  InvestmentInsight,
  CareGuide,
} from './types';

// ─── Products ────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-seiko-001',
    slug: 'seiko-presage-cocktail-time-srpb43j1',
    name: 'Presage Cocktail Time',
    modelName: 'Presage Cocktail Time',
    brand: 'Seiko',
    reference_number: 'SRPB43J1',
    referenceNumber: 'SRPB43J1',
    price: 45000,
    purchaseValue: 45000,
    currency: 'INR',
    images: ['/watches/seiko-presage-srpb43j1.png'],
    imageUrl: '/watches/seiko-presage-srpb43j1.png',
    description: 'Inspired by the glamour of Tokyo cocktail bars. Features an ice-blue sunburst guilloché dial, polished dauphine hands, blued steel second hand, and a box-shaped crystal.',
    craftsmanship_narrative: 'Powered by the Seiko 4R35 mechanical automatic calibre with 41-hour power reserve and exhibition caseback.',
    movement_type: 'Automatic',
    movementType: 'Automatic',
    movement_caliber: 'Cal. 4R35',
    case_size: '40.5 mm',
    caseSize: '40.5 mm',
    dial_color: 'Ice Blue',
    crystal: 'Box-shaped Hardlex',
    strap_options: [
      { id: 'so-seiko-1', material: 'Black Leather with Blue Stitching', color: 'Black/Blue', price_addon: 0 },
      { id: 'so-seiko-2', material: 'Stainless Steel Mesh', color: 'Steel', price_addon: 3500 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 8,
    stockCount: 8,
    collection: 'Presage',
    tags: ['cocktail-time', 'dress', 'sunburst', 'mechanical'],
    isActive: true,
  },
  {
    id: 'prod-titan-002',
    slug: 'titan-edge-ceramic-slim-1696qc01',
    name: 'Edge Ceramic Slim',
    modelName: 'Edge Ceramic Slim',
    brand: 'Titan',
    reference_number: '1696QC01',
    referenceNumber: '1696QC01',
    price: 24995,
    purchaseValue: 24995,
    currency: 'INR',
    images: ['/watches/titan-edge.jpg'],
    imageUrl: '/watches/titan-edge.jpg',
    description: 'One of the slimmest ceramic watches in the world at just 4.4 mm total thickness. Hypoallergenic high-tech ceramic case and bracelet with a pure minimalist dial.',
    craftsmanship_narrative: 'Engineered with Titan’s proprietary ultra-slim Edge quartz movement with state-of-the-art precision regulation.',
    movement_type: 'Quartz',
    movementType: 'Quartz',
    movement_caliber: 'Titan Ultra-Slim Edge Calibre',
    case_size: '40 mm',
    caseSize: '40 mm',
    dial_color: 'Anthracite Black',
    crystal: 'Sapphire Crystal',
    strap_options: [
      { id: 'so-titan-1', material: 'High-Tech Ceramic Bracelet', color: 'Black', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 6,
    stockCount: 6,
    collection: 'Edge',
    tags: ['ultra-slim', 'ceramic', 'contemporary', 'titan'],
    isActive: true,
  },
  {
    id: 'prod-fastrack-003',
    slug: 'fastrack-reflex-play-38072ap01',
    name: 'Reflex Play Analog-Digital',
    modelName: 'Reflex Play Analog-Digital',
    brand: 'Fastrack',
    reference_number: '38072AP01',
    referenceNumber: '38072AP01',
    price: 4495,
    purchaseValue: 4495,
    currency: 'INR',
    images: ['/watches/fastrack-reflex.jpg'],
    imageUrl: '/watches/fastrack-reflex.jpg',
    description: 'Dynamic sports timepiece combining analog hand tracking with digital LCD stopwatch, alarm, and second-timezone instrumentation.',
    craftsmanship_narrative: 'Impact-resistant matte resin case with reinforced mineral crystal and sweat-wicking silicone strap.',
    movement_type: 'Quartz',
    movementType: 'Quartz',
    movement_caliber: 'Dual Time Ana-Digi Module',
    case_size: '44 mm',
    caseSize: '44 mm',
    dial_color: 'Stealth Black / Crimson',
    crystal: 'Hardened Mineral',
    strap_options: [
      { id: 'so-fastrack-1', material: 'Silicone Sports Band', color: 'Black', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 15,
    stockCount: 15,
    collection: 'Reflex',
    tags: ['sport', 'dual-time', 'analog-digital', 'active'],
    isActive: true,
  },
  {
    id: 'prod-sonata-004',
    slug: 'sonata-volt-champagne-classic-77083ym01',
    name: 'Volt Champagne Classic',
    modelName: 'Volt Champagne Classic',
    brand: 'Sonata',
    reference_number: '77083YM01',
    referenceNumber: '77083YM01',
    price: 1895,
    purchaseValue: 1895,
    currency: 'INR',
    images: ['/watches/sonata-volt.jpg'],
    imageUrl: '/watches/sonata-volt.jpg',
    description: 'Timeless traditional formal watch with a shimmering champagne dial, gold-polished fluted case, and durable stainless steel link bracelet.',
    craftsmanship_narrative: 'Engineered for enduring reliability with a high-accuracy quartz oscillator and mineral glass.',
    movement_type: 'Quartz',
    movementType: 'Quartz',
    movement_caliber: 'Japanese Quartz Calibre',
    case_size: '39 mm',
    caseSize: '39 mm',
    dial_color: 'Champagne Gold',
    crystal: 'Mineral Glass',
    strap_options: [
      { id: 'so-sonata-1', material: 'Gold-Plated Stainless Steel', color: 'Gold', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 20,
    stockCount: 20,
    collection: 'Volt',
    tags: ['classic', 'gold', 'formal', 'dress'],
    isActive: true,
  },
  {
    id: 'prod-timex-005',
    slug: 'timex-q-timex-reissue-1979-tw2t80700',
    name: 'Q Timex Reissue 1979',
    modelName: 'Q Timex Reissue 1979',
    brand: 'Timex',
    reference_number: 'TW2T80700',
    referenceNumber: 'TW2T80700',
    price: 13995,
    purchaseValue: 13995,
    currency: 'INR',
    images: ['/watches/timex-q.png'],
    imageUrl: '/watches/timex-q.png',
    description: 'Faithful recreation of the iconic 1979 quartz diver. Features a bidirectional red and blue "Pepsi" rotating ring, woven stainless steel bracelet, functional battery hatch, and domed acrylic crystal.',
    craftsmanship_narrative: 'Period-correct vintage geometry featuring hooded lugs and luminous dial geometry.',
    movement_type: 'Quartz',
    movementType: 'Quartz',
    movement_caliber: 'Seiko Epson Quartz Calibre',
    case_size: '38 mm',
    caseSize: '38 mm',
    dial_color: 'Matte Deep Blue',
    crystal: 'Domed Acrylic',
    strap_options: [
      { id: 'so-timex-1', material: 'Woven Stainless Steel Bracelet', color: 'Steel', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 10,
    stockCount: 10,
    collection: 'Q Timex',
    tags: ['pepsi-bezel', 'retro', 'heritage', 'woven-steel'],
    isActive: true,
  },
  {
    id: 'prod-casio-006',
    slug: 'casio-g-shock-octagonal-ga-2100-1a1dr',
    name: 'G-Shock Octagonal "CasiOak"',
    modelName: 'G-Shock Octagonal "CasiOak"',
    brand: 'Casio',
    reference_number: 'GA-2100-1A1DR',
    referenceNumber: 'GA-2100-1A1DR',
    price: 9195,
    purchaseValue: 9195,
    currency: 'INR',
    images: ['/watches/casio-ga2100.png'],
    imageUrl: '/watches/casio-ga2100.png',
    description: 'The world-famous octagonal Carbon Core Guard G-Shock in full stealth matte black. Ultra-thin 11.8mm profile with extraordinary shock resistance.',
    craftsmanship_narrative: 'Carbon Core Guard structure protects the internal module by enclosing it in a carbon-reinforced fine resin case.',
    movement_type: 'Quartz',
    movementType: 'Quartz',
    movement_caliber: 'Casio Module 5611',
    case_size: '45.4 mm',
    caseSize: '45.4 mm',
    dial_color: 'Stealth Blackout',
    crystal: 'Mineral Glass',
    strap_options: [
      { id: 'so-casio-1', material: 'Resin Strap', color: 'Stealth Black', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 12,
    stockCount: 12,
    collection: 'G-Shock Carbon Core',
    tags: ['casioak', 'stealth', 'carbon-core', 'shockproof'],
    isActive: true,
  },
  {
    id: 'prod-fossil-007',
    slug: 'fossil-townsman-automatic-skeleton-me3098',
    name: 'Townsman Automatic Skeleton',
    modelName: 'Townsman Automatic Skeleton',
    brand: 'Fossil',
    reference_number: 'ME3098',
    referenceNumber: 'ME3098',
    price: 18995,
    purchaseValue: 18995,
    currency: 'INR',
    images: ['/watches/fossil-townsman.png'],
    imageUrl: '/watches/fossil-townsman.png',
    description: 'Striking open-work skeleton dial revealing the intricate balance wheel and gear train. Rose gold accents contrasted with a rich amber leather strap.',
    craftsmanship_narrative: 'Rotor-powered automatic self-winding movement with exhibition case back showing full mechanical operation.',
    movement_type: 'Automatic',
    movementType: 'Automatic',
    movement_caliber: 'Miyota Skeleton Automatic',
    case_size: '44 mm',
    caseSize: '44 mm',
    dial_color: 'Skeleton / Rose Gold & Charcoal',
    crystal: 'Hardened Mineral',
    strap_options: [
      { id: 'so-fossil-1', material: 'Genuine Leather Strap', color: 'Amber Brown', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 7,
    stockCount: 7,
    collection: 'Townsman',
    tags: ['skeleton', 'mechanical', 'rose-gold', 'leather'],
    isActive: true,
  },
  {
    id: 'prod-citizen-008',
    slug: 'citizen-promaster-marine-eco-drive-bn0150-28e',
    name: 'Promaster Marine Eco-Drive Diver',
    modelName: 'Promaster Marine Eco-Drive Diver',
    brand: 'Citizen',
    reference_number: 'BN0150-28E',
    referenceNumber: 'BN0150-28E',
    price: 28500,
    purchaseValue: 28500,
    currency: 'INR',
    images: ['/watches/citizen-promaster.webp'],
    imageUrl: '/watches/citizen-promaster.webp',
    description: 'ISO 6425 compliant professional saturation dive watch. Powered by any light source via Eco-Drive technology, never requiring a battery change.',
    craftsmanship_narrative: 'Features an oversized high-visibility luminous handset, 60-click unidirectional ratcheting bezel, and screw-down crown at 4 o’clock.',
    movement_type: 'Eco-Drive Solar',
    movementType: 'Eco-Drive Solar',
    movement_caliber: 'Calibre E168 Eco-Drive',
    case_size: '44 mm',
    caseSize: '44 mm',
    dial_color: 'Matte Deep Black',
    crystal: 'Anti-Reflective Mineral Crystal',
    strap_options: [
      { id: 'so-citizen-1', material: 'Polyurethane Accordion Diver Strap', color: 'Black', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 9,
    stockCount: 9,
    collection: 'Promaster',
    tags: ['diver', 'eco-drive', 'solar', 'iso-certified'],
    isActive: true,
  },
  {
    id: 'prod-tissot-009',
    slug: 'tissot-prx-powermatic-80-t137-407-11-041-00',
    name: 'PRX Powermatic 80',
    modelName: 'PRX Powermatic 80',
    brand: 'Tissot',
    reference_number: 'T137.407.11.041.00',
    referenceNumber: 'T137.407.11.041.00',
    price: 68000,
    purchaseValue: 68000,
    currency: 'INR',
    images: ['/watches/tissot-prx.png'],
    imageUrl: '/watches/tissot-prx.png',
    description: 'The defining integrated-bracelet sports watch of our era. 1978 retro tonneau silhouette with a deeply textured blue waffle dial and exhibition sapphire caseback.',
    craftsmanship_narrative: 'Equipped with the groundbreaking Swiss Powermatic 80 calibre with 80 hours of power reserve and anti-magnetic Nivachron hairspring.',
    movement_type: 'Automatic',
    movementType: 'Automatic',
    movement_caliber: 'Powermatic 80.111',
    case_size: '40 mm',
    caseSize: '40 mm',
    dial_color: 'Waffle Embossed Blue',
    crystal: 'Scratch-resistant Sapphire Crystal',
    strap_options: [
      { id: 'so-tissot-1', material: 'Integrated 316L Stainless Steel', color: 'Steel', price_addon: 0 },
      { id: 'so-tissot-2', material: 'FKM Textured Rubber', color: 'Navy Blue', price_addon: 4500 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 5,
    stockCount: 5,
    collection: 'PRX',
    tags: ['integrated-bracelet', 'swiss-made', 'powermatic-80', 'blue-dial'],
    isActive: true,
  },
  {
    id: 'prod-tag-010',
    slug: 'tag-heuer-carrera-chronograph-cbs2210-fc6534',
    name: 'Carrera Chronograph Glassbox',
    modelName: 'Carrera Chronograph Glassbox',
    brand: 'TAG Heuer',
    reference_number: 'CBS2210.FC6534',
    referenceNumber: 'CBS2210.FC6534',
    price: 560000,
    purchaseValue: 560000,
    currency: 'INR',
    images: ['/watches/tag-heuer-carrera.jpg'],
    imageUrl: '/watches/tag-heuer-carrera.jpg',
    description: '60th anniversary glassbox edition with seamless domed sapphire crystal curving over the tachymeter scale. Reverse panda tri-compax layout with perforated leather racing strap.',
    craftsmanship_narrative: 'Manufacture Calibre TH20-00 automatic chronograph with bidirectional winding rotor and 80-hour power reserve.',
    movement_type: 'Automatic',
    movementType: 'Automatic',
    movement_caliber: 'Heuer 02 / TH20-00 In-House',
    case_size: '39 mm',
    caseSize: '39 mm',
    dial_color: 'Signature Glassbox Black & Silver',
    crystal: 'Domed Beveled Sapphire Crystal',
    strap_options: [
      { id: 'so-tag-1', material: 'Perforated Racing Calfskin Leather', color: 'Black', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 4,
    stockCount: 4,
    collection: 'Carrera',
    tags: ['chronograph', 'motorsport', 'glassbox', 'in-house'],
    isActive: true,
  },
  {
    id: 'prod-rado-011',
    slug: 'rado-captain-cook-automatic-r32505313',
    name: 'Captain Cook Automatic',
    modelName: 'Captain Cook Automatic',
    brand: 'Rado',
    reference_number: 'R32505313',
    referenceNumber: 'R32505313',
    price: 215000,
    purchaseValue: 215000,
    currency: 'INR',
    images: ['/watches/rado-captain-cook.png'],
    imageUrl: '/watches/rado-captain-cook.png',
    description: 'Vintage diver aesthetics fused with Rado’s Master of Materials innovation. Features an inward-sloping high-tech ceramic bezel insert, sunbrushed gradient green dial, and swinging red anchor.',
    craftsmanship_narrative: 'Swiss automatic calibre with 80 hours power reserve and Nivachron anti-magnetic balance spring.',
    movement_type: 'Automatic',
    movementType: 'Automatic',
    movement_caliber: 'Calibre R763',
    case_size: '42 mm',
    caseSize: '42 mm',
    dial_color: 'Sunbrushed Forest Green',
    crystal: 'Box Sapphire with Anti-Reflective Coating',
    strap_options: [
      { id: 'so-rado-1', material: 'Beads of Rice Stainless Steel Bracelet', color: 'Steel', price_addon: 0 },
      { id: 'so-rado-2', material: 'Vintage Tanned Leather', color: 'Tobacco Brown', price_addon: 6500 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 4,
    stockCount: 4,
    collection: 'Captain Cook',
    tags: ['high-tech-ceramic', 'vintage-diver', 'swiss-made', 'green-dial'],
    isActive: true,
  },
  {
    id: 'prod-omega-012',
    slug: 'omega-speedmaster-professional-moonwatch-31030425001002',
    name: 'Speedmaster Professional Moonwatch',
    modelName: 'Speedmaster Professional Moonwatch',
    brand: 'Omega',
    reference_number: '310.30.42.50.01.002',
    referenceNumber: '310.30.42.50.01.002',
    price: 790000,
    purchaseValue: 790000,
    currency: 'INR',
    images: ['/watches/omega-speedmaster.png'],
    imageUrl: '/watches/omega-speedmaster.png',
    description: 'The legendary Moonwatch. Direct descendant of the timepiece flight-qualified by NASA for all manned lunar expeditions. Features the anodised aluminium bezel ring with "Dot over 90".',
    craftsmanship_narrative: 'Powered by the Master Chronometer-certified Calibre 3861 manual-wind movement, resistant to magnetic fields reaching 15,000 gauss.',
    movement_type: 'Manual',
    movementType: 'Manual',
    movement_caliber: 'Co-Axial Master Chronometer Cal. 3861',
    case_size: '42 mm',
    caseSize: '42 mm',
    dial_color: 'Step Matte Black',
    crystal: 'Sapphire Crystal with Anti-Reflective Treatment',
    strap_options: [
      { id: 'so-omega-1', material: 'Stainless Steel Bracelet with Comfort Clasp', color: 'Steel', price_addon: 0 },
      { id: 'so-omega-2', material: 'NASA-Certified Velcro Flight Strap', color: 'Black', price_addon: 12000 },
    ],
    condition: 'New',
    in_stock: true,
    inStock: true,
    stock: 3,
    stockCount: 3,
    collection: 'Speedmaster',
    tags: ['moonwatch', 'nasa', 'co-axial', 'chronograph'],
    isActive: true,
  },
];

// ─── Vault Items (Demo Data) ──────────────────────────────────

export const MOCK_VAULT_ITEMS: VaultItem[] = [
  {
    id: 'vault-001',
    owner_id: 'user-demo',
    watch_name: 'Presage Cocktail Time',
    brand: 'Seiko',
    reference_number: 'SRPB43J1',
    movement: 'Calibre 4R35 — Automatic',
    case_size: '40.5 mm',
    dial_color: 'Ice Blue Sunburst',
    strap_material: 'Leather Strap with Blue Stitching',
    photo_urls: ['/watches/seiko-presage-srpb43j1.png'],
    document_urls: [],
    purchase_date: '2023-04-12',
    purchase_price: 45000,
    last_service_date: '2024-02-15',
    service_due_date: '2027-02-15',
    health_status: 'Excellent',
    serial_number: 'SK449182',
    year_of_manufacture: 2023,
    notes: 'Full set. Box and papers.',
    service_history: [
      {
        id: 'sh-001',
        vault_item_id: 'vault-001',
        date: '2024-02-15',
        service_type: 'Regulation & Accuracy Calibration',
        description: 'Complete timing diagnostics and magnetic demagnetization performed.',
        technician_name: 'Arjun Mehta',
        cost: 4500,
        warranty_until: '2025-02-15',
      },
    ],
    created_at: '2023-04-12T10:00:00Z',
  },
  {
    id: 'vault-002',
    owner_id: 'user-demo',
    watch_name: 'PRX Powermatic 80',
    brand: 'Tissot',
    reference_number: 'T137.407.11.041.00',
    movement: 'Powermatic 80.111 — Automatic',
    case_size: '40 mm',
    dial_color: 'Waffle Blue',
    strap_material: 'Integrated Stainless Steel',
    photo_urls: ['/watches/tissot-prx.png'],
    document_urls: [],
    purchase_date: '2022-08-10',
    purchase_price: 68000,
    last_service_date: '2023-08-10',
    service_due_date: '2026-08-10',
    health_status: 'Excellent',
    serial_number: 'TS994121',
    year_of_manufacture: 2022,
    notes: 'Daily atelier wearer. Nivachron hairspring in perfect condition.',
    service_history: [],
    created_at: '2022-08-10T14:30:00Z',
  },
  {
    id: 'vault-003',
    owner_id: 'user-demo',
    watch_name: 'Speedmaster Professional Moonwatch',
    brand: 'Omega',
    reference_number: '310.30.42.50.01.002',
    movement: 'Calibre 3861 — Manual Wind',
    case_size: '42 mm',
    dial_color: 'Step Matte Black',
    strap_material: 'Stainless Steel Bracelet',
    photo_urls: ['/watches/omega-speedmaster.png'],
    document_urls: [],
    purchase_date: '2024-01-20',
    purchase_price: 790000,
    last_service_date: undefined,
    service_due_date: '2029-01-20',
    health_status: 'Excellent',
    serial_number: 'OG8892102',
    year_of_manufacture: 2024,
    notes: 'Acquired brand new. Master Chronometer certificate registered.',
    service_history: [],
    created_at: '2024-01-20T09:15:00Z',
  },
];

// ─── Technicians ─────────────────────────────────────────────

export const MOCK_TECHNICIANS: Technician[] = [
  {
    id: 'tech-001',
    user_id: 'user-tech-001',
    name: 'Arjun Mehta',
    portrait_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=85',
    bio: 'A WOSTEP-certified master watchmaker with 18 years of experience in Swiss luxury horology. Arjun trained at the École d\'Horlogerie in Le Locle before returning to India to establish Wristloom\'s technical division. He has serviced watches ranging from Patek Philippe perpetual calendars to Rolex professional models, and his precision is unmatched across the platform.',
    years_experience: 18,
    certifications: [
      { id: 'cert-001', name: 'WOSTEP Master Watchmaker', issuer: 'WOSTEP', issued_at: '2010-06-15' },
      { id: 'cert-002', name: 'Rolex Service Certification', issuer: 'Rolex SA', issued_at: '2015-03-01' },
      { id: 'cert-003', name: 'Patek Philippe Accredited Service', issuer: 'Patek Philippe SA', issued_at: '2018-09-20' },
    ],
    specializations: ['Complicated Movements', 'Vintage Restoration', 'Tourbillons', 'Perpetual Calendars'],
    brands_serviced: ['Rolex', 'Patek Philippe', 'Audemars Piguet', 'A. Lange & Söhne', 'Vacheron Constantin'],
    rating: 4.97,
    completed_services: 847,
    available: true,
    reviews: [],
  },
  {
    id: 'tech-002',
    user_id: 'user-tech-002',
    name: 'Priya Nair',
    portrait_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=85',
    bio: 'Priya is a specialist in Japanese horology and Spring Drive movements, having spent four years at the Grand Seiko Shinshu Watch Studio in Japan. She holds dual certification in Swiss and Japanese watchmaking traditions, making her uniquely qualified to handle the intersection of Eastern and Western luxury watchmaking.',
    years_experience: 11,
    certifications: [
      { id: 'cert-004', name: 'Grand Seiko Authorised Technician', issuer: 'Seiko Watch Corporation', issued_at: '2017-04-10' },
      { id: 'cert-005', name: 'BHI Fellowship', issuer: 'British Horological Institute', issued_at: '2019-11-08' },
    ],
    specializations: ['Spring Drive Movements', 'Japanese Horology', 'Quartz Precision', 'Crystal Replacement'],
    brands_serviced: ['Grand Seiko', 'Seiko', 'Citizen', 'Omega', 'Longines'],
    rating: 4.93,
    completed_services: 512,
    available: true,
    reviews: [],
  },
  {
    id: 'tech-003',
    user_id: 'user-tech-003',
    name: 'Vikram Rao',
    portrait_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=85',
    bio: 'Vikram specialises in sports and professional watches — chronographs, dive watches, and pilot\'s timepieces. With 14 years of experience and a background in precision engineering, his technical eye is unparalleled when it comes to high-complication sporting movements.',
    years_experience: 14,
    certifications: [
      { id: 'cert-006', name: 'IWC Authorised Service Technician', issuer: 'IWC Schaffhausen', issued_at: '2016-07-22' },
      { id: 'cert-007', name: 'TAG Heuer Master Technician', issuer: 'TAG Heuer', issued_at: '2018-02-14' },
      { id: 'cert-008', name: 'Omega METAS Certified', issuer: 'Omega SA', issued_at: '2021-05-30' },
    ],
    specializations: ['Chronographs', 'Dive Watch Service', 'Pilot Watches', 'Water Resistance Testing'],
    brands_serviced: ['Omega', 'IWC', 'TAG Heuer', 'Breitling', 'Panerai', 'Tudor'],
    rating: 4.89,
    completed_services: 673,
    available: false,
    reviews: [],
  },
];

// ─── Reviews ─────────────────────────────────────────────────

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    technician_id: 'tech-001',
    customer_name: 'Rohit Sharma',
    rating: 5,
    title: 'Patek Philippe in perfect hands',
    body: 'I was understandably nervous handing over my 5711 for a full service. Arjun was meticulous in his communication throughout — sending photos at each stage, explaining the condition of every component. The watch came back running to COSC standards. I will not trust this to anyone else.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Patek Philippe',
    created_at: '2024-09-15T10:30:00Z',
    verified: true,
  },
  {
    id: 'rev-002',
    technician_id: 'tech-001',
    customer_name: 'Ananya Krishnan',
    rating: 5,
    title: 'The gold standard in house-call service',
    body: 'The entire experience was exceptional. Arjun arrived exactly on time, set up a portable service station in our living room, and completed a regulation service on my A. Lange & Söhne while I watched. The precision and care he applied was extraordinary. Worth every rupee.',
    service_type: 'Regulation & Timing',
    watch_brand: 'A. Lange & Söhne',
    created_at: '2024-08-22T14:15:00Z',
    verified: true,
  },
  {
    id: 'rev-003',
    technician_id: 'tech-002',
    customer_name: 'Deepak Menon',
    rating: 5,
    title: 'The only person who truly understands Spring Drive',
    body: 'My Grand Seiko SBGA211 had a peculiar timing irregularity that three other watchmakers could not diagnose. Priya identified a worn glide spring within minutes of examination and had it sorted within the week. Her understanding of the Spring Drive mechanism is genuinely rare.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Grand Seiko',
    created_at: '2024-10-01T09:00:00Z',
    verified: true,
  },
  {
    id: 'rev-004',
    technician_id: 'tech-003',
    customer_name: 'Sanjay Patel',
    rating: 5,
    title: 'Chronograph serviced to factory specification',
    body: 'Vikram serviced my vintage Omega Speedmaster and the results were beyond expectations. The movement was cleaned, oiled, and regulated to within 2 seconds per day. The hesalite crystal was polished to near-new condition. He even sent me a timing machine readout before and after.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Omega',
    created_at: '2024-07-18T11:45:00Z',
    verified: true,
  },
];

// ─── Testimonials ────────────────────────────────────────────

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    customer_name: 'Ravi Desai',
    customer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=85',
    customer_location: 'Mumbai',
    service_type: 'Watch Vault & Authentication',
    watch_brand: 'Rolex',
    title: 'This is what watch ownership should feel like.',
    body: 'I have collected watches for fifteen years. Wristloom is the first platform that understands what ownership actually means — not just the transaction, but everything that comes after. My Watch Vault has become the definitive record of my collection, and the authentication service gave me complete confidence in my recent pre-owned Submariner purchase.',
    rating: 5,
    featured: true,
    created_at: '2024-11-10T08:00:00Z',
  },
  {
    id: 'test-002',
    customer_name: 'Meera Iyer',
    customer_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=85',
    customer_location: 'Bengaluru',
    service_type: 'House-Call Repair',
    watch_brand: 'Omega',
    title: 'A technician in my living room felt like a privilege.',
    body: 'The house-call service completely changed how I think about watch care. Arjun arrived with a portable service station, explained every step of the crystal replacement on my Speedmaster, and finished within two hours. The real-time tracking meant I never felt out of the loop. I\'ve recommended Wristloom to everyone in my collector circle.',
    rating: 5,
    featured: true,
    created_at: '2024-10-25T15:30:00Z',
  },
  {
    id: 'test-003',
    customer_name: 'Karan Verma',
    customer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85',
    customer_location: 'Delhi',
    service_type: 'Trade-In & Purchase',
    watch_brand: 'Audemars Piguet',
    title: 'The trade-in programme is genuinely brilliant.',
    body: 'I used the trade-in credit from my old TAG Heuer toward the repair of my AP Royal Oak, and later toward a workshop session. The closed-loop economy Wristloom has built is something I haven\'t seen anywhere else. This isn\'t a shop — it\'s an ecosystem.',
    rating: 5,
    featured: true,
    created_at: '2024-09-30T12:00:00Z',
  },
  {
    id: 'test-004',
    customer_name: 'Ayesha Kapoor',
    customer_location: 'Pune',
    service_type: 'Watch-Building Workshop',
    title: 'Building my own watch was life-changing.',
    body: 'I attended the beginner workshop on a whim and left with a profound appreciation for the craft. The master watchmaker guided us through every component — the escapement, the mainspring, the jewel settings. I now understand why a Patek Philippe costs what it costs. My assembled watch sits in my Vault alongside my purchased pieces.',
    rating: 5,
    featured: false,
    created_at: '2024-08-15T10:00:00Z',
  },
];

// ─── Restoration Projects ─────────────────────────────────────

export const MOCK_RESTORATIONS: RestorationProject[] = [
  {
    id: 'rest-001',
    technician_id: 'tech-001',
    watch_brand: 'Rolex',
    watch_model: 'Datejust 1601',
    reference_number: '1601',
    work_performed: [
      'Complete movement disassembly and ultrasonic cleaning',
      'Replacement of all worn gaskets and seals',
      'Dial restoration — removal of moisture staining',
      'Replacement of damaged tritium indices with period-correct service parts',
      'Full case and bracelet refinishing — satin and mirror polish',
      'Movement regulation to +2/-1 seconds per day',
      'Water resistance testing to factory specification',
    ],
    before_images: [
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&q=85',
    ],
    after_images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=85',
    ],
    duration_days: 32,
    completed_at: '2024-08-20T00:00:00Z',
    description: 'A 1972 Rolex Datejust arrived in neglected condition — the movement had not been serviced in over a decade, the dial showed moisture ingress, and the case finish was heavily worn. A comprehensive restoration over 32 days returned it to a condition indistinguishable from new.',
    featured: true,
  },
  {
    id: 'rest-002',
    technician_id: 'tech-002',
    watch_brand: 'Grand Seiko',
    watch_model: 'SBGT001',
    reference_number: 'SBGT001',
    work_performed: [
      'Spring Drive movement full service',
      'Glide spring replacement',
      'Titanium case re-finishing with zaratsu polishing technique',
      'Dial cleaning and light restoration',
      'Crown and stem replacement',
    ],
    before_images: [
      'https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800&q=85',
    ],
    after_images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=85',
    ],
    duration_days: 18,
    completed_at: '2024-09-12T00:00:00Z',
    description: 'A rare first-generation Grand Seiko Spring Drive requiring specialist knowledge of the proprietary movement. The titanium case zaratsu polishing was performed by hand to the same standard as the original Shinshu studio.',
    featured: true,
  },
];

// ─── Workshops ───────────────────────────────────────────────

export const MOCK_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-001',
    title: 'The Anatomy of a Watch — Beginner Assembly',
    description: 'Guided by a master watchmaker, you will disassemble, understand, and reassemble a Swiss lever escapement movement. No prior experience required. You leave with a fully assembled timepiece and a digital assembly record added to your Wristloom Vault.',
    instructor_name: 'Arjun Mehta',
    instructor_bio: 'WOSTEP Master Watchmaker with 18 years experience across Swiss luxury brands.',
    duration_hours: 4,
    max_participants: 8,
    current_participants: 5,
    price: 28000,
    difficulty: 'Beginner',
    location: 'Wristloom Atelier, Mumbai',
    cover_image_url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&q=85',
    components_available: [
      { id: 'comp-001', name: 'Steel Case', description: 'Brushed 316L stainless steel case, 38mm', material: 'Stainless Steel', price_addon: 0 },
      { id: 'comp-002', name: 'Rose Gold PVD Case', description: 'Rose gold PVD-coated steel case, 38mm', material: 'PVD Steel', price_addon: 4500 },
      { id: 'comp-003', name: 'White Dial', description: 'Lacquered white dial with applied indices', material: 'Lacquered Brass', price_addon: 0 },
      { id: 'comp-004', name: 'Black Sunburst Dial', description: 'Sunburst-finished black dial', material: 'Lacquered Brass', price_addon: 2200 },
    ],
    dates: [
      { id: 'date-001', date: '2025-10-18', time: '10:00 AM', spots_remaining: 3 },
      { id: 'date-002', date: '2025-11-08', time: '10:00 AM', spots_remaining: 5 },
      { id: 'date-003', date: '2025-11-22', time: '2:00 PM', spots_remaining: 8 },
    ],
  },
  {
    id: 'ws-002',
    title: 'Chronograph Mastery — Intermediate',
    description: 'An immersive full-day workshop focusing on column wheel chronograph movements. Participants will service a donor movement, learn to set the chronograph mechanism, and understand the engineering behind split-second timing.',
    instructor_name: 'Vikram Rao',
    instructor_bio: 'Specialist in chronograph and sporting movements, IWC and Omega certified.',
    duration_hours: 7,
    max_participants: 6,
    current_participants: 4,
    price: 45000,
    difficulty: 'Intermediate',
    location: 'Wristloom Atelier, Mumbai',
    cover_image_url: 'https://images.unsplash.com/photo-1509941943102-10c232535736?w=800&q=85',
    components_available: [
      { id: 'comp-005', name: 'Standard Steel Case', description: '40mm steel pilot-style case', material: 'Stainless Steel', price_addon: 0 },
    ],
    dates: [
      { id: 'date-004', date: '2025-10-25', time: '9:00 AM', spots_remaining: 2 },
      { id: 'date-005', date: '2025-11-15', time: '9:00 AM', spots_remaining: 4 },
    ],
  },
];

// ─── Community Posts ──────────────────────────────────────────

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-001',
    author_id: 'user-001',
    author_name: 'Ravi Desai',
    author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=85',
    title: 'How I built a 12-piece collection over 20 years — and what I\'d do differently',
    body: 'When I bought my first watch — a Longines Conquest in 2004 — I had no idea it would lead to where I am today. Here is everything I\'ve learned about building a serious collection without the regrets...',
    category: 'story',
    image_urls: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=85'],
    watch_brands: ['Longines', 'Omega', 'Rolex', 'Patek Philippe'],
    likes: 247,
    comment_count: 38,
    featured: true,
    created_at: '2024-10-15T09:00:00Z',
  },
  {
    id: 'post-002',
    author_id: 'user-002',
    author_name: 'Meera Iyer',
    author_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=85',
    title: 'The Spring Drive explained — why it changed my understanding of horology',
    body: 'Until I attended Priya\'s workshop at Wristloom, I didn\'t understand why anyone would pay a premium for a Spring Drive over a standard automatic. After three hours with an open movement, everything changed...',
    category: 'discussion',
    watch_brands: ['Grand Seiko'],
    likes: 183,
    comment_count: 22,
    featured: true,
    created_at: '2024-09-28T14:30:00Z',
  },
  {
    id: 'post-003',
    author_id: 'user-003',
    author_name: 'Karan Verma',
    title: 'My AP Royal Oak restoration — a 45-day journey',
    body: 'Six months ago, I acquired a 1990s Royal Oak in heavily worn condition. What followed was the most educational — and occasionally stressful — watch ownership experience of my life...',
    category: 'restoration',
    image_urls: ['https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=600&q=85'],
    watch_brands: ['Audemars Piguet'],
    likes: 312,
    comment_count: 51,
    featured: true,
    created_at: '2024-11-02T10:00:00Z',
  },
];

// ─── FAQ Items ────────────────────────────────────────────────

export const MOCK_FAQ: FAQItem[] = [
  {
    id: 'faq-001',
    category: 'House-Call Repairs',
    question: 'How does the house-call repair service work?',
    answer: 'Our certified technicians come directly to your home or office. You select a repair service, enter your address, choose a time slot, and pay a deposit to confirm your booking. On the day of service, you can track your technician\'s location in real time via the Wristloom app. After the service, a detailed service record is added to your Watch Vault automatically.',
  },
  {
    id: 'faq-002',
    category: 'House-Call Repairs',
    question: 'Are my watches insured during a house-call service?',
    answer: 'Yes. All watches under house-call service are covered by Wristloom\'s comprehensive service insurance policy from the moment the technician arrives until it is returned to your hands. This covers accidental damage, loss, and theft during the service window.',
  },
  {
    id: 'faq-003',
    category: 'Authentication',
    question: 'What does the authentication process involve?',
    answer: 'Our multi-stage authentication involves component inspection (movement, case, dial, hands, crown), reference and serial number verification against manufacturer records, condition analysis, documentation review, and a final certification by our lead horologist. The entire process typically takes 5–10 business days.',
  },
  {
    id: 'faq-004',
    category: 'Authentication',
    question: 'Do you authenticate all watch brands?',
    answer: 'We specialise in Swiss and Japanese luxury watches — Rolex, Patek Philippe, Audemars Piguet, Omega, IWC, Jaeger-LeCoultre, Grand Seiko, and more. If your brand is not listed, contact us and we will advise on whether we can assist.',
  },
  {
    id: 'faq-005',
    category: 'Trade-Ins',
    question: 'How is my trade-in value calculated?',
    answer: 'Trade-in valuations are based on current secondary market data, the watch\'s condition, completeness (box and papers), service history, and demand. We provide a valuation within 3 business days of receiving your submission. The final credit offer is valid for 30 days.',
  },
  {
    id: 'faq-006',
    category: 'Trade-Ins',
    question: 'What can I use trade-in credit for?',
    answer: 'Trade-in credit can be applied toward any watch purchase, repair service, restoration project, or workshop booking on the Wristloom platform. Credits do not expire and can be split across multiple transactions.',
  },
  {
    id: 'faq-007',
    category: 'Watch Vault',
    question: 'Is my Watch Vault data secure?',
    answer: 'Yes. Your Watch Vault is accessible only to you. All uploaded documents and photographs are encrypted at rest and in transit. We do not share your collection data with third parties under any circumstances. You can download or delete your data at any time.',
  },
  {
    id: 'faq-008',
    category: 'Service Warranties',
    question: 'What warranty do you provide on repair work?',
    answer: 'All repair services carry a minimum 12-month warranty covering the specific work performed. Full service and overhaul work is warranted for 24 months. If any issue related to our work arises within the warranty period, we will rectify it at no charge.',
  },
  {
    id: 'faq-009',
    category: 'Shipping',
    question: 'How do you handle shipping for sent-in repairs?',
    answer: 'We provide fully insured, double-boxed shipping labels for all sent-in repairs. Watches are collected by our secure courier partner and arrive at our atelier sealed and documented. You receive photo evidence of arrival within 24 hours of collection.',
  },
  {
    id: 'faq-010',
    category: 'Payments',
    question: 'What payment methods do you accept?',
    answer: 'We accept all major credit and debit cards, UPI, net banking, and Wristloom platform credits. EMI options are available for purchases above ₹50,000 through select card issuers. All transactions are processed securely through Razorpay.',
  },
];

// ─── Service Locations ────────────────────────────────────────

export const MOCK_LOCATIONS: Location[] = [
  { id: 'loc-001', city: 'Mumbai', region: 'Maharashtra', country: 'India', coverage_area: 'South Mumbai, Bandra, Juhu, Andheri, Powai', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication', 'Workshop', 'Concierge'] },
  { id: 'loc-002', city: 'Delhi', region: 'Delhi NCR', country: 'India', coverage_area: 'Lutyens Delhi, Greater Kailash, Defence Colony, Gurugram, Noida', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication', 'Concierge'] },
  { id: 'loc-003', city: 'Bengaluru', region: 'Karnataka', country: 'India', coverage_area: 'Indiranagar, Koramangala, Whitefield, Jayanagar', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication'] },
  { id: 'loc-004', city: 'Hyderabad', region: 'Telangana', country: 'India', coverage_area: 'Jubilee Hills, Banjara Hills, Gachibowli, Madhapur', availability_status: 'Limited', services_available: ['House-Call Repair'] },
  { id: 'loc-005', city: 'Chennai', region: 'Tamil Nadu', country: 'India', coverage_area: 'Nungambakkam, Adyar, Boat Club', availability_status: 'Limited', services_available: ['House-Call Repair'] },
  { id: 'loc-006', city: 'Pune', region: 'Maharashtra', country: 'India', coverage_area: 'Koregaon Park, Kalyani Nagar, Viman Nagar', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication'] },
  { id: 'loc-007', city: 'Kolkata', region: 'West Bengal', country: 'India', coverage_area: 'Alipore, Ballygunge, Park Street', availability_status: 'Coming Soon', services_available: [] },
  { id: 'loc-008', city: 'Ahmedabad', region: 'Gujarat', country: 'India', coverage_area: 'Satellite, Vastrapur, Bodakdev', availability_status: 'Coming Soon', services_available: [] },
];

// ─── Care Guides ──────────────────────────────────────────────

export const MOCK_CARE_GUIDES: CareGuide[] = [
  {
    id: 'guide-001',
    slug: 'mechanical-watch-winding',
    title: 'How to wind and set a mechanical watch correctly',
    category: 'mechanical',
    excerpt: 'Incorrect winding is one of the most common causes of mainspring damage. Learn the right technique for manual and automatic movements.',
    body: '',
    read_time_minutes: 6,
    published_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'guide-002',
    slug: 'watch-storage-guide',
    title: 'The definitive guide to storing your watch collection',
    category: 'storage',
    excerpt: 'Whether you own one watch or one hundred, correct storage prevents invisible damage that accumulates over years.',
    body: '',
    read_time_minutes: 8,
    published_at: '2024-09-15T00:00:00Z',
  },
  {
    id: 'guide-003',
    slug: 'water-resistance-truth',
    title: 'What your water resistance rating actually means',
    category: 'water-resistance',
    excerpt: '30m water resistance does not mean you can wear your watch while washing your hands. The ratings are more nuanced than the numbers suggest.',
    body: '',
    read_time_minutes: 5,
    published_at: '2024-10-01T00:00:00Z',
  },
];

// ─── Horological Journal & Heritage Chronicles ───────────────

export const MOCK_INVESTMENT_INSIGHTS: InvestmentInsight[] = [
  {
    id: 'ins-001',
    slug: 'swiss-mechanical-horology-legacy',
    title: 'The Enduring Legacy of Swiss Mechanical Horology',
    excerpt: 'Exploring how heritage ateliers maintain precision manufacturing, mechanical longevity, and timeless architectural design across centuries.',
    body: '',
    brand_focus: 'Rolex & Geneva Ateliers',
    read_time_minutes: 10,
    published_at: '2024-11-01T00:00:00Z',
    disclaimer: 'Curated editorial archive from the Wristloom Horological Atelier celebrating classic craftsmanship.',
  },
  {
    id: 'ins-002',
    slug: 'grand-seiko-spring-drive-craft',
    title: 'Grand Seiko & The Mastery of Spring Drive Regulation',
    excerpt: 'An in-depth look at how master artisans bridged quartz regulation and mechanical drive in the Shinshu Watch Studio.',
    body: '',
    brand_focus: 'Grand Seiko',
    read_time_minutes: 8,
    published_at: '2024-10-15T00:00:00Z',
    disclaimer: 'Curated editorial archive from the Wristloom Horological Atelier celebrating classic craftsmanship.',
  },
];
