// ============================================================
// Wristloom — Realistic Mock Data
// All images use high-quality Unsplash URLs for luxury watches
// ============================================================

import type {
  VaultItem,
  Technician,
  Product,
  TradeInRequest,
  AppraisalRequest,
  Review,
  Testimonial,
  Workshop,
  RestorationProject,
  CommunityPost,
  FAQItem,
  Location,
  InvestmentInsight,
  CareGuide,
} from './types';

// ─── Products ────────────────────────────────────────────────

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'prod-001',
    slug: 'rolex-submariner-date-126610ln',
    name: 'Submariner Date',
    brand: 'Rolex',
    reference_number: '126610LN',
    price: 1450000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=800&q=90',
      'https://images.unsplash.com/photo-1526045431048-f857369baa09?w=800&q=90',
      'https://images.unsplash.com/photo-1612817288484-6f916006741a?w=800&q=90',
    ],
    description: 'The reference in professional dive watches. The Submariner Date combines technical performance underwater with the refinement expected of a Rolex timepiece.',
    craftsmanship_narrative: 'Crafted in Rolex\'s Oystersteel, the Submariner case is machined from a single block of metal—a process that takes weeks. The unidirectional Cerachrom bezel insert, made from virtually scratchproof ceramic, is processed in two colours using a single piece of material through a proprietary patent-pending technique.',
    movement_type: 'Automatic',
    movement_caliber: 'Cal. 3235',
    power_reserve: '70 hours',
    case_material: 'Oystersteel (904L)',
    case_size: '41mm',
    case_thickness: '12.5mm',
    dial_color: 'Black',
    crystal: 'Sapphire with Cyclops lens',
    water_resistance: '300m / 1,000ft',
    strap_options: [
      { id: 'so-001', material: 'Oystersteel Oyster Bracelet', color: 'Steel', price_addon: 0 },
      { id: 'so-002', material: 'Rubber', color: 'Black', price_addon: 12000 },
    ],
    condition: 'New',
    in_stock: true,
    collection: 'Oyster Professional',
    tags: ['dive', 'professional', 'iconic', 'steel'],
  },
  {
    id: 'prod-002',
    slug: 'patek-philippe-nautilus-5711-1a',
    name: 'Nautilus',
    brand: 'Patek Philippe',
    reference_number: '5711/1A-010',
    price: 8500000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=90',
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=90',
    ],
    description: 'Designed by Gérald Genta in 1976, the Nautilus is arguably the most coveted sports watch ever created. Its porthole-inspired case and horizontally embossed dial are instantly recognisable.',
    craftsmanship_narrative: 'The integrated stainless steel bracelet required 138 hand-finishing operations when it was introduced. Each link is bevelled, brushed, and polished in alternating finishes—a labour of precision that has never been compromised. The movement is visible through the exhibition caseback, decorated with the Côtes de Genève pattern.',
    movement_type: 'Automatic',
    movement_caliber: 'Cal. 26-330 S C',
    power_reserve: '45 hours',
    case_material: 'Stainless Steel',
    case_size: '40mm',
    case_thickness: '8.3mm',
    dial_color: 'Blue',
    crystal: 'Sapphire',
    water_resistance: '120m',
    strap_options: [
      { id: 'so-003', material: 'Stainless Steel', color: 'Steel/Blue', price_addon: 0 },
    ],
    condition: 'Certified Pre-Owned',
    year: 2021,
    in_stock: true,
    collection: 'Nautilus',
    tags: ['sports', 'iconic', 'steel', 'blue-dial'],
  },
  {
    id: 'prod-003',
    slug: 'audemars-piguet-royal-oak-15500st',
    name: 'Royal Oak',
    brand: 'Audemars Piguet',
    reference_number: '15500ST.OO.1220ST.01',
    price: 6800000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=800&q=90',
      'https://images.unsplash.com/photo-1526045431048-f857369baa09?w=800&q=90',
    ],
    description: 'The watch that redefined luxury in 1972. Gerald Genta\'s octagonal bezel secured by eight hexagonal screws remains one of the most daring designs in horology.',
    craftsmanship_narrative: 'The Grande Tapisserie dial pattern — achieved through a pantograph-guided cutting tool that takes three days to complete per dial — has remained unchanged since 1972. Each of the 8 screws on the bezel is hand-finished and aligned at the same angle: a standard of consistency that requires a watchmaker\'s loupe.',
    movement_type: 'Automatic',
    movement_caliber: 'Cal. 4302',
    power_reserve: '60 hours',
    case_material: 'Stainless Steel',
    case_size: '41mm',
    case_thickness: '9.8mm',
    dial_color: 'Blue',
    crystal: 'Sapphire',
    water_resistance: '50m',
    strap_options: [
      { id: 'so-004', material: 'Stainless Steel Bracelet', color: 'Steel', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    collection: 'Royal Oak',
    tags: ['iconic', 'sports-luxury', 'steel'],
  },
  {
    id: 'prod-004',
    slug: 'omega-speedmaster-professional-31030425001002',
    name: 'Speedmaster Professional Moonwatch',
    brand: 'Omega',
    reference_number: '310.30.42.50.01.002',
    price: 540000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1587925358603-c2eea5305bbc?w=800&q=90',
      'https://images.unsplash.com/photo-1509941943102-10c232535736?w=800&q=90',
    ],
    description: 'The watch that went to the Moon. Hand-wound, astronaut-tested, and unchanged in spirit since 1957. The Speedmaster Professional remains the only watch certified by NASA for Extra Vehicular Activity.',
    craftsmanship_narrative: 'The hesalite crystal — chosen over sapphire for its shatter-resistance in the vacuum of space — is hand-polished on a lathe. The iconic tachymetre scale on the bezel is achieved through an enamel filling process that requires multiple firings and precision grinding.',
    movement_type: 'Manual',
    movement_caliber: 'Cal. 3861',
    power_reserve: '50 hours',
    case_material: 'Stainless Steel',
    case_size: '42mm',
    case_thickness: '13.2mm',
    dial_color: 'Black',
    crystal: 'Hesalite',
    water_resistance: '50m',
    strap_options: [
      { id: 'so-005', material: 'NATO Nylon', color: 'Black/Grey', price_addon: 0 },
      { id: 'so-006', material: 'Stainless Steel Bracelet', color: 'Steel', price_addon: 18000 },
    ],
    condition: 'New',
    in_stock: true,
    collection: 'Moonwatch',
    tags: ['chronograph', 'nasa', 'iconic', 'manual-wind'],
  },
  {
    id: 'prod-005',
    slug: 'iwc-portugieser-chronograph-iw371615',
    name: 'Portugieser Chronograph',
    brand: 'IWC Schaffhausen',
    reference_number: 'IW371615',
    price: 890000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=90',
      'https://images.unsplash.com/photo-1523170335258-f5ed11844a49?w=800&q=90',
    ],
    description: 'The Portugieser Chronograph embodies the essence of elegant watchmaking. Its clean, legible dial and precision timekeeping have made it a cornerstone of the IWC collection.',
    craftsmanship_narrative: 'The movement, Calibre 69355, features a column wheel mechanism — the hallmark of a serious chronograph — visible through the exhibition caseback. Each component is hand-decorated with circular Côtes de Genève striping, a tradition maintained by IWC\'s in-house craftsmen.',
    movement_type: 'Automatic',
    movement_caliber: 'Cal. 69355',
    power_reserve: '46 hours',
    case_material: 'Stainless Steel',
    case_size: '41mm',
    dial_color: 'Silver',
    crystal: 'Sapphire',
    water_resistance: '30m',
    strap_options: [
      { id: 'so-007', material: 'Alligator Leather', color: 'Brown', price_addon: 0 },
      { id: 'so-008', material: 'Stainless Steel', color: 'Steel', price_addon: 22000 },
    ],
    condition: 'New',
    in_stock: true,
    collection: 'Portugieser',
    tags: ['chronograph', 'dress', 'elegant'],
  },
  {
    id: 'prod-006',
    slug: 'grand-seiko-snowflake-sbga211',
    name: 'Snowflake',
    brand: 'Grand Seiko',
    reference_number: 'SBGA211',
    price: 780000,
    currency: 'INR',
    images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=90',
      'https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800&q=90',
    ],
    description: 'The Snowflake dial, inspired by the snow-covered forests of the Shinshu region, is hand-crafted with a textured surface that captures light differently at every angle.',
    craftsmanship_narrative: 'Each Snowflake dial is individually created by artisans at the Shinshu Watch Studio. The zaratsu-polished case requires over 30 individual polishing steps, alternating between flat and curved surfaces, to achieve the mirror-like finish that Grand Seiko considers non-negotiable.',
    movement_type: 'Spring Drive',
    movement_caliber: 'Cal. 9R65',
    power_reserve: '72 hours',
    case_material: 'Titanium',
    case_size: '41mm',
    case_thickness: '11mm',
    dial_color: 'White/Ivory',
    crystal: 'Sapphire',
    water_resistance: '100m',
    strap_options: [
      { id: 'so-009', material: 'Titanium Bracelet', color: 'Titanium', price_addon: 0 },
    ],
    condition: 'New',
    in_stock: true,
    collection: 'Seasons',
    tags: ['spring-drive', 'titanium', 'artisanal', 'japan'],
  },
];

// ─── Vault Items (Demo Data) ──────────────────────────────────

export const MOCK_VAULT_ITEMS: VaultItem[] = [
  {
    id: 'vault-001',
    owner_id: 'user-demo',
    watch_name: 'Submariner Date',
    brand: 'Rolex',
    reference_number: '126610LN',
    movement: 'Calibre 3235 — Self-Winding',
    case_size: '41mm',
    dial_color: 'Black',
    strap_material: 'Oystersteel Oyster Bracelet',
    photo_urls: [
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?w=600&q=85',
    ],
    document_urls: [],
    purchase_date: '2022-03-15',
    purchase_price: 1380000,
    last_service_date: '2023-08-10',
    service_due_date: '2028-08-10',
    health_status: 'Excellent',
    serial_number: '2MZ49817',
    year_of_manufacture: 2022,
    notes: 'Full set. Box and papers. Purchased from authorised retailer.',
    service_history: [
      {
        id: 'sh-001',
        vault_item_id: 'vault-001',
        date: '2023-08-10',
        service_type: 'Full Service & Overhaul',
        description: 'Complete movement service, gasket replacement, water resistance test, bracelet service.',
        technician_name: 'Arjun Mehta',
        cost: 22000,
        warranty_until: '2024-08-10',
      },
    ],
    created_at: '2022-03-16T10:00:00Z',
  },
  {
    id: 'vault-002',
    owner_id: 'user-demo',
    watch_name: 'Speedmaster Professional',
    brand: 'Omega',
    reference_number: '310.30.42.50.01.002',
    movement: 'Calibre 3861 — Manual',
    case_size: '42mm',
    dial_color: 'Black',
    strap_material: 'NATO Nylon',
    photo_urls: [
      'https://images.unsplash.com/photo-1587925358603-c2eea5305bbc?w=600&q=85',
    ],
    document_urls: [],
    purchase_date: '2021-07-20',
    purchase_price: 520000,
    last_service_date: '2021-07-20',
    service_due_date: '2026-07-20',
    health_status: 'Service Recommended',
    serial_number: 'OG7741220',
    year_of_manufacture: 2021,
    notes: 'Heritage piece. Original bracelet retained as spare.',
    service_history: [],
    created_at: '2021-07-21T14:30:00Z',
  },
  {
    id: 'vault-003',
    owner_id: 'user-demo',
    watch_name: 'Royal Oak',
    brand: 'Audemars Piguet',
    reference_number: '15500ST.OO.1220ST.01',
    movement: 'Calibre 4302 — Self-Winding',
    case_size: '41mm',
    dial_color: 'Blue',
    strap_material: 'Stainless Steel Bracelet',
    photo_urls: [
      'https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=600&q=85',
    ],
    document_urls: [],
    purchase_date: '2023-11-05',
    purchase_price: 6750000,
    last_service_date: undefined,
    service_due_date: '2028-11-05',
    health_status: 'Excellent',
    serial_number: 'AP3318872',
    year_of_manufacture: 2023,
    notes: 'Acquired via certified pre-owned dealer. Full warranty transferred.',
    service_history: [],
    created_at: '2023-11-06T09:15:00Z',
  },
];

// ─── Technicians ─────────────────────────────────────────────

export const MOCK_TECHNICIANS: Technician[] = [
  {
    id: 'tech-001',
    user_id: 'user-tech-001',
    name: 'Arjun Mehta',
    portrait_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&q=85',
    bio: 'A WOSTEP-certified master watchmaker with 18 years of experience in Swiss luxury horology. Arjun trained at the École d\'Horlogerie in Le Locle before returning to India to establish Wristloom\'s technical division. He has serviced watches ranging from Patek Philippe perpetual calendars to Rolex professional models, and his precision is unmatched across the platform.',
    years_experience: 18,
    certifications: [
      { id: 'cert-001', name: 'WOSTEP Master Watchmaker', issuer: 'WOSTEP', issued_at: '2010-06-15' },
      { id: 'cert-002', name: 'Rolex Service Certification', issuer: 'Rolex SA', issued_at: '2015-03-01' },
      { id: 'cert-003', name: 'Patek Philippe Accredited Service', issuer: 'Patek Philippe SA', issued_at: '2018-09-20' },
    ],
    specializations: ['Complicated Movements', 'Vintage Restoration', 'Tourbillons', 'Perpetual Calendars'],
    brands_serviced: ['Rolex', 'Patek Philippe', 'Audemars Piguet', 'A. Lange & Söhne', 'Vacheron Constantin'],
    rating: 4.97,
    completed_services: 847,
    available: true,
    reviews: [],
  },
  {
    id: 'tech-002',
    user_id: 'user-tech-002',
    name: 'Priya Nair',
    portrait_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&q=85',
    bio: 'Priya is a specialist in Japanese horology and Spring Drive movements, having spent four years at the Grand Seiko Shinshu Watch Studio in Japan. She holds dual certification in Swiss and Japanese watchmaking traditions, making her uniquely qualified to handle the intersection of Eastern and Western luxury watchmaking.',
    years_experience: 11,
    certifications: [
      { id: 'cert-004', name: 'Grand Seiko Authorised Technician', issuer: 'Seiko Watch Corporation', issued_at: '2017-04-10' },
      { id: 'cert-005', name: 'BHI Fellowship', issuer: 'British Horological Institute', issued_at: '2019-11-08' },
    ],
    specializations: ['Spring Drive Movements', 'Japanese Horology', 'Quartz Precision', 'Crystal Replacement'],
    brands_serviced: ['Grand Seiko', 'Seiko', 'Citizen', 'Omega', 'Longines'],
    rating: 4.93,
    completed_services: 512,
    available: true,
    reviews: [],
  },
  {
    id: 'tech-003',
    user_id: 'user-tech-003',
    name: 'Vikram Rao',
    portrait_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&q=85',
    bio: 'Vikram specialises in sports and professional watches — chronographs, dive watches, and pilot\'s timepieces. With 14 years of experience and a background in precision engineering, his technical eye is unparalleled when it comes to high-complication sporting movements.',
    years_experience: 14,
    certifications: [
      { id: 'cert-006', name: 'IWC Authorised Service Technician', issuer: 'IWC Schaffhausen', issued_at: '2016-07-22' },
      { id: 'cert-007', name: 'TAG Heuer Master Technician', issuer: 'TAG Heuer', issued_at: '2018-02-14' },
      { id: 'cert-008', name: 'Omega METAS Certified', issuer: 'Omega SA', issued_at: '2021-05-30' },
    ],
    specializations: ['Chronographs', 'Dive Watch Service', 'Pilot Watches', 'Water Resistance Testing'],
    brands_serviced: ['Omega', 'IWC', 'TAG Heuer', 'Breitling', 'Panerai', 'Tudor'],
    rating: 4.89,
    completed_services: 673,
    available: false,
    reviews: [],
  },
];

// ─── Reviews ─────────────────────────────────────────────────

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'rev-001',
    technician_id: 'tech-001',
    customer_name: 'Rohit Sharma',
    rating: 5,
    title: 'Patek Philippe in perfect hands',
    body: 'I was understandably nervous handing over my 5711 for a full service. Arjun was meticulous in his communication throughout — sending photos at each stage, explaining the condition of every component. The watch came back running to COSC standards. I will not trust this to anyone else.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Patek Philippe',
    created_at: '2024-09-15T10:30:00Z',
    verified: true,
  },
  {
    id: 'rev-002',
    technician_id: 'tech-001',
    customer_name: 'Ananya Krishnan',
    rating: 5,
    title: 'The gold standard in house-call service',
    body: 'The entire experience was exceptional. Arjun arrived exactly on time, set up a portable service station in our living room, and completed a regulation service on my A. Lange & Söhne while I watched. The precision and care he applied was extraordinary. Worth every rupee.',
    service_type: 'Regulation & Timing',
    watch_brand: 'A. Lange & Söhne',
    created_at: '2024-08-22T14:15:00Z',
    verified: true,
  },
  {
    id: 'rev-003',
    technician_id: 'tech-002',
    customer_name: 'Deepak Menon',
    rating: 5,
    title: 'The only person who truly understands Spring Drive',
    body: 'My Grand Seiko SBGA211 had a peculiar timing irregularity that three other watchmakers could not diagnose. Priya identified a worn glide spring within minutes of examination and had it sorted within the week. Her understanding of the Spring Drive mechanism is genuinely rare.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Grand Seiko',
    created_at: '2024-10-01T09:00:00Z',
    verified: true,
  },
  {
    id: 'rev-004',
    technician_id: 'tech-003',
    customer_name: 'Sanjay Patel',
    rating: 5,
    title: 'Chronograph serviced to factory specification',
    body: 'Vikram serviced my vintage Omega Speedmaster and the results were beyond expectations. The movement was cleaned, oiled, and regulated to within 2 seconds per day. The hesalite crystal was polished to near-new condition. He even sent me a timing machine readout before and after.',
    service_type: 'Full Service & Overhaul',
    watch_brand: 'Omega',
    created_at: '2024-07-18T11:45:00Z',
    verified: true,
  },
];

// ─── Testimonials ────────────────────────────────────────────

export const MOCK_TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    customer_name: 'Ravi Desai',
    customer_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=200&q=85',
    customer_location: 'Mumbai',
    service_type: 'Watch Vault & Authentication',
    watch_brand: 'Rolex',
    title: 'This is what watch ownership should feel like.',
    body: 'I have collected watches for fifteen years. Wristloom is the first platform that understands what ownership actually means — not just the transaction, but everything that comes after. My Watch Vault has become the definitive record of my collection, and the authentication service gave me complete confidence in my recent pre-owned Submariner purchase.',
    rating: 5,
    featured: true,
    created_at: '2024-11-10T08:00:00Z',
  },
  {
    id: 'test-002',
    customer_name: 'Meera Iyer',
    customer_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&q=85',
    customer_location: 'Bengaluru',
    service_type: 'House-Call Repair',
    watch_brand: 'Omega',
    title: 'A technician in my living room felt like a privilege.',
    body: 'The house-call service completely changed how I think about watch care. Arjun arrived with a portable service station, explained every step of the crystal replacement on my Speedmaster, and finished within two hours. The real-time tracking meant I never felt out of the loop. I\'ve recommended Wristloom to everyone in my collector circle.',
    rating: 5,
    featured: true,
    created_at: '2024-10-25T15:30:00Z',
  },
  {
    id: 'test-003',
    customer_name: 'Karan Verma',
    customer_avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&q=85',
    customer_location: 'Delhi',
    service_type: 'Trade-In & Purchase',
    watch_brand: 'Audemars Piguet',
    title: 'The trade-in programme is genuinely brilliant.',
    body: 'I used the trade-in credit from my old TAG Heuer toward the repair of my AP Royal Oak, and later toward a workshop session. The closed-loop economy Wristloom has built is something I haven\'t seen anywhere else. This isn\'t a shop — it\'s an ecosystem.',
    rating: 5,
    featured: true,
    created_at: '2024-09-30T12:00:00Z',
  },
  {
    id: 'test-004',
    customer_name: 'Ayesha Kapoor',
    customer_location: 'Pune',
    service_type: 'Watch-Building Workshop',
    title: 'Building my own watch was life-changing.',
    body: 'I attended the beginner workshop on a whim and left with a profound appreciation for the craft. The master watchmaker guided us through every component — the escapement, the mainspring, the jewel settings. I now understand why a Patek Philippe costs what it costs. My assembled watch sits in my Vault alongside my purchased pieces.',
    rating: 5,
    featured: false,
    created_at: '2024-08-15T10:00:00Z',
  },
];

// ─── Restoration Projects ─────────────────────────────────────

export const MOCK_RESTORATIONS: RestorationProject[] = [
  {
    id: 'rest-001',
    technician_id: 'tech-001',
    watch_brand: 'Rolex',
    watch_model: 'Datejust 1601',
    reference_number: '1601',
    work_performed: [
      'Complete movement disassembly and ultrasonic cleaning',
      'Replacement of all worn gaskets and seals',
      'Dial restoration — removal of moisture staining',
      'Replacement of damaged tritium indices with period-correct service parts',
      'Full case and bracelet refinishing — satin and mirror polish',
      'Movement regulation to +2/-1 seconds per day',
      'Water resistance testing to factory specification',
    ],
    before_images: [
      'https://images.unsplash.com/photo-1533139502658-0198f920d8e8?w=800&q=85',
    ],
    after_images: [
      'https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=800&q=85',
    ],
    duration_days: 32,
    completed_at: '2024-08-20T00:00:00Z',
    description: 'A 1972 Rolex Datejust arrived in neglected condition — the movement had not been serviced in over a decade, the dial showed moisture ingress, and the case finish was heavily worn. A comprehensive restoration over 32 days returned it to a condition indistinguishable from new.',
    featured: true,
  },
  {
    id: 'rest-002',
    technician_id: 'tech-002',
    watch_brand: 'Grand Seiko',
    watch_model: 'SBGT001',
    reference_number: 'SBGT001',
    work_performed: [
      'Spring Drive movement full service',
      'Glide spring replacement',
      'Titanium case re-finishing with zaratsu polishing technique',
      'Dial cleaning and light restoration',
      'Crown and stem replacement',
    ],
    before_images: [
      'https://images.unsplash.com/photo-1585123334904-845d60e97b29?w=800&q=85',
    ],
    after_images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&q=85',
    ],
    duration_days: 18,
    completed_at: '2024-09-12T00:00:00Z',
    description: 'A rare first-generation Grand Seiko Spring Drive requiring specialist knowledge of the proprietary movement. The titanium case zaratsu polishing was performed by hand to the same standard as the original Shinshu studio.',
    featured: true,
  },
];

// ─── Workshops ───────────────────────────────────────────────

export const MOCK_WORKSHOPS: Workshop[] = [
  {
    id: 'ws-001',
    title: 'The Anatomy of a Watch — Beginner Assembly',
    description: 'Guided by a master watchmaker, you will disassemble, understand, and reassemble a Swiss lever escapement movement. No prior experience required. You leave with a fully assembled timepiece and a digital assembly record added to your Wristloom Vault.',
    instructor_name: 'Arjun Mehta',
    instructor_bio: 'WOSTEP Master Watchmaker with 18 years experience across Swiss luxury brands.',
    duration_hours: 4,
    max_participants: 8,
    current_participants: 5,
    price: 28000,
    difficulty: 'Beginner',
    location: 'Wristloom Atelier, Mumbai',
    cover_image_url: 'https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&q=85',
    components_available: [
      { id: 'comp-001', name: 'Steel Case', description: 'Brushed 316L stainless steel case, 38mm', material: 'Stainless Steel', price_addon: 0 },
      { id: 'comp-002', name: 'Rose Gold PVD Case', description: 'Rose gold PVD-coated steel case, 38mm', material: 'PVD Steel', price_addon: 4500 },
      { id: 'comp-003', name: 'White Dial', description: 'Lacquered white dial with applied indices', material: 'Lacquered Brass', price_addon: 0 },
      { id: 'comp-004', name: 'Black Sunburst Dial', description: 'Sunburst-finished black dial', material: 'Lacquered Brass', price_addon: 2200 },
    ],
    dates: [
      { id: 'date-001', date: '2025-10-18', time: '10:00 AM', spots_remaining: 3 },
      { id: 'date-002', date: '2025-11-08', time: '10:00 AM', spots_remaining: 5 },
      { id: 'date-003', date: '2025-11-22', time: '2:00 PM', spots_remaining: 8 },
    ],
  },
  {
    id: 'ws-002',
    title: 'Chronograph Mastery — Intermediate',
    description: 'An immersive full-day workshop focusing on column wheel chronograph movements. Participants will service a donor movement, learn to set the chronograph mechanism, and understand the engineering behind split-second timing.',
    instructor_name: 'Vikram Rao',
    instructor_bio: 'Specialist in chronograph and sporting movements, IWC and Omega certified.',
    duration_hours: 7,
    max_participants: 6,
    current_participants: 4,
    price: 45000,
    difficulty: 'Intermediate',
    location: 'Wristloom Atelier, Mumbai',
    cover_image_url: 'https://images.unsplash.com/photo-1509941943102-10c232535736?w=800&q=85',
    components_available: [
      { id: 'comp-005', name: 'Standard Steel Case', description: '40mm steel pilot-style case', material: 'Stainless Steel', price_addon: 0 },
    ],
    dates: [
      { id: 'date-004', date: '2025-10-25', time: '9:00 AM', spots_remaining: 2 },
      { id: 'date-005', date: '2025-11-15', time: '9:00 AM', spots_remaining: 4 },
    ],
  },
];

// ─── Community Posts ──────────────────────────────────────────

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-001',
    author_id: 'user-001',
    author_name: 'Ravi Desai',
    author_avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&q=85',
    title: 'How I built a 12-piece collection over 20 years — and what I\'d do differently',
    body: 'When I bought my first watch — a Longines Conquest in 2004 — I had no idea it would lead to where I am today. Here is everything I\'ve learned about building a serious collection without the regrets...',
    category: 'story',
    image_urls: ['https://images.unsplash.com/photo-1614164185128-e4ec99c436d7?w=600&q=85'],
    watch_brands: ['Longines', 'Omega', 'Rolex', 'Patek Philippe'],
    likes: 247,
    comment_count: 38,
    featured: true,
    created_at: '2024-10-15T09:00:00Z',
  },
  {
    id: 'post-002',
    author_id: 'user-002',
    author_name: 'Meera Iyer',
    author_avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&q=85',
    title: 'The Spring Drive explained — why it changed my understanding of horology',
    body: 'Until I attended Priya\'s workshop at Wristloom, I didn\'t understand why anyone would pay a premium for a Spring Drive over a standard automatic. After three hours with an open movement, everything changed...',
    category: 'discussion',
    watch_brands: ['Grand Seiko'],
    likes: 183,
    comment_count: 22,
    featured: true,
    created_at: '2024-09-28T14:30:00Z',
  },
  {
    id: 'post-003',
    author_id: 'user-003',
    author_name: 'Karan Verma',
    title: 'My AP Royal Oak restoration — a 45-day journey',
    body: 'Six months ago, I acquired a 1990s Royal Oak in heavily worn condition. What followed was the most educational — and occasionally stressful — watch ownership experience of my life...',
    category: 'restoration',
    image_urls: ['https://images.unsplash.com/photo-1548169874-53e85f753f1e?w=600&q=85'],
    watch_brands: ['Audemars Piguet'],
    likes: 312,
    comment_count: 51,
    featured: true,
    created_at: '2024-11-02T10:00:00Z',
  },
];

// ─── FAQ Items ────────────────────────────────────────────────

export const MOCK_FAQ: FAQItem[] = [
  {
    id: 'faq-001',
    category: 'House-Call Repairs',
    question: 'How does the house-call repair service work?',
    answer: 'Our certified technicians come directly to your home or office. You select a repair service, enter your address, choose a time slot, and pay a deposit to confirm your booking. On the day of service, you can track your technician\'s location in real time via the Wristloom app. After the service, a detailed service record is added to your Watch Vault automatically.',
  },
  {
    id: 'faq-002',
    category: 'House-Call Repairs',
    question: 'Are my watches insured during a house-call service?',
    answer: 'Yes. All watches under house-call service are covered by Wristloom\'s comprehensive service insurance policy from the moment the technician arrives until it is returned to your hands. This covers accidental damage, loss, and theft during the service window.',
  },
  {
    id: 'faq-003',
    category: 'Authentication',
    question: 'What does the authentication process involve?',
    answer: 'Our multi-stage authentication involves component inspection (movement, case, dial, hands, crown), reference and serial number verification against manufacturer records, condition analysis, documentation review, and a final certification by our lead horologist. The entire process typically takes 5–10 business days.',
  },
  {
    id: 'faq-004',
    category: 'Authentication',
    question: 'Do you authenticate all watch brands?',
    answer: 'We specialise in Swiss and Japanese luxury watches — Rolex, Patek Philippe, Audemars Piguet, Omega, IWC, Jaeger-LeCoultre, Grand Seiko, and more. If your brand is not listed, contact us and we will advise on whether we can assist.',
  },
  {
    id: 'faq-005',
    category: 'Trade-Ins',
    question: 'How is my trade-in value calculated?',
    answer: 'Trade-in valuations are based on current secondary market data, the watch\'s condition, completeness (box and papers), service history, and demand. We provide a valuation within 3 business days of receiving your submission. The final credit offer is valid for 30 days.',
  },
  {
    id: 'faq-006',
    category: 'Trade-Ins',
    question: 'What can I use trade-in credit for?',
    answer: 'Trade-in credit can be applied toward any watch purchase, repair service, restoration project, or workshop booking on the Wristloom platform. Credits do not expire and can be split across multiple transactions.',
  },
  {
    id: 'faq-007',
    category: 'Watch Vault',
    question: 'Is my Watch Vault data secure?',
    answer: 'Yes. Your Watch Vault is accessible only to you. All uploaded documents and photographs are encrypted at rest and in transit. We do not share your collection data with third parties under any circumstances. You can download or delete your data at any time.',
  },
  {
    id: 'faq-008',
    category: 'Service Warranties',
    question: 'What warranty do you provide on repair work?',
    answer: 'All repair services carry a minimum 12-month warranty covering the specific work performed. Full service and overhaul work is warranted for 24 months. If any issue related to our work arises within the warranty period, we will rectify it at no charge.',
  },
  {
    id: 'faq-009',
    category: 'Shipping',
    question: 'How do you handle shipping for sent-in repairs?',
    answer: 'We provide fully insured, double-boxed shipping labels for all sent-in repairs. Watches are collected by our secure courier partner and arrive at our atelier sealed and documented. You receive photo evidence of arrival within 24 hours of collection.',
  },
  {
    id: 'faq-010',
    category: 'Payments',
    question: 'What payment methods do you accept?',
    answer: 'We accept all major credit and debit cards, UPI, net banking, and Wristloom platform credits. EMI options are available for purchases above ₹50,000 through select card issuers. All transactions are processed securely through Razorpay.',
  },
];

// ─── Service Locations ────────────────────────────────────────

export const MOCK_LOCATIONS: Location[] = [
  { id: 'loc-001', city: 'Mumbai', region: 'Maharashtra', country: 'India', coverage_area: 'South Mumbai, Bandra, Juhu, Andheri, Powai', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication', 'Workshop', 'Concierge'] },
  { id: 'loc-002', city: 'Delhi', region: 'Delhi NCR', country: 'India', coverage_area: 'Lutyens Delhi, Greater Kailash, Defence Colony, Gurugram, Noida', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication', 'Concierge'] },
  { id: 'loc-003', city: 'Bengaluru', region: 'Karnataka', country: 'India', coverage_area: 'Indiranagar, Koramangala, Whitefield, Jayanagar', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication'] },
  { id: 'loc-004', city: 'Hyderabad', region: 'Telangana', country: 'India', coverage_area: 'Jubilee Hills, Banjara Hills, Gachibowli, Madhapur', availability_status: 'Limited', services_available: ['House-Call Repair'] },
  { id: 'loc-005', city: 'Chennai', region: 'Tamil Nadu', country: 'India', coverage_area: 'Nungambakkam, Adyar, Boat Club', availability_status: 'Limited', services_available: ['House-Call Repair'] },
  { id: 'loc-006', city: 'Pune', region: 'Maharashtra', country: 'India', coverage_area: 'Koregaon Park, Kalyani Nagar, Viman Nagar', availability_status: 'Available', services_available: ['House-Call Repair', 'Authentication'] },
  { id: 'loc-007', city: 'Kolkata', region: 'West Bengal', country: 'India', coverage_area: 'Alipore, Ballygunge, Park Street', availability_status: 'Coming Soon', services_available: [] },
  { id: 'loc-008', city: 'Ahmedabad', region: 'Gujarat', country: 'India', coverage_area: 'Satellite, Vastrapur, Bodakdev', availability_status: 'Coming Soon', services_available: [] },
];

// ─── Care Guides ──────────────────────────────────────────────

export const MOCK_CARE_GUIDES: CareGuide[] = [
  {
    id: 'guide-001',
    slug: 'mechanical-watch-winding',
    title: 'How to wind and set a mechanical watch correctly',
    category: 'mechanical',
    excerpt: 'Incorrect winding is one of the most common causes of mainspring damage. Learn the right technique for manual and automatic movements.',
    body: '',
    read_time_minutes: 6,
    published_at: '2024-09-01T00:00:00Z',
  },
  {
    id: 'guide-002',
    slug: 'watch-storage-guide',
    title: 'The definitive guide to storing your watch collection',
    category: 'storage',
    excerpt: 'Whether you own one watch or one hundred, correct storage prevents invisible damage that accumulates over years.',
    body: '',
    read_time_minutes: 8,
    published_at: '2024-09-15T00:00:00Z',
  },
  {
    id: 'guide-003',
    slug: 'water-resistance-truth',
    title: 'What your water resistance rating actually means',
    category: 'water-resistance',
    excerpt: '30m water resistance does not mean you can wear your watch while washing your hands. The ratings are more nuanced than the numbers suggest.',
    body: '',
    read_time_minutes: 5,
    published_at: '2024-10-01T00:00:00Z',
  },
];

// ─── Investment Insights ──────────────────────────────────────

export const MOCK_INVESTMENT_INSIGHTS: InvestmentInsight[] = [
  {
    id: 'ins-001',
    slug: 'rolex-secondary-market-2024',
    title: 'The Rolex secondary market in 2024 — a data-driven perspective',
    excerpt: 'After the speculative peaks of 2021 and 2022, the secondary market has entered a period of normalisation. What does this mean for collectors?',
    body: '',
    brand_focus: 'Rolex',
    read_time_minutes: 12,
    published_at: '2024-11-01T00:00:00Z',
    disclaimer: 'This article is for educational purposes only. Wristloom does not provide investment advice. Watch values can decrease as well as increase.',
  },
  {
    id: 'ins-002',
    slug: 'grand-seiko-appreciation',
    title: 'Grand Seiko\'s quiet ascent — understanding the value trajectory',
    excerpt: 'Once regarded as a curiosity outside Japan, Grand Seiko has become one of the most discussed names in serious collecting circles.',
    body: '',
    brand_focus: 'Grand Seiko',
    read_time_minutes: 9,
    published_at: '2024-10-15T00:00:00Z',
    disclaimer: 'This article is for educational purposes only. Past appreciation does not predict future performance.',
  },
];
